### ISSUE TITLE
TypeError on ManyToOne relation fields with empty asset restrictions

### ISSUE THREAD

**Issue by ArianJuwig** [BlackbitDigitalCommerce/pimcore-data-director#144]
Pimcore Version: 10.6.9
Data Director Version: 3.5.46

Replicatable with an empty asset restriction in the related classes ManyToOne relation property:
<img width="888" alt="Bildschirmfoto 2024-03-05 um 10 13 27" src="https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/115006609/1476b67f-8709-4e40-aaed-82e986bd6d08">
 

DD response/Stacktrace by opening the dataports attribute mapping:

```JSON
{
  "success": false,
  "dataport": {
  "id": 1,
  "name": "XXX"
},
  "errorMessage": "TypeError: Cannot access offset of type string on string in /var/www/html/vendor/blackbit/data-director/lib/Pim/Helper.php:3419\nStack trace:\n#0 /var/www/html/vendor/blackbit/data-director/lib/Pim/Helper.php(673): Blackbit\\DataDirectorBundle\\lib\\Pim\\Helper->getTemplates()\n#1 /var/www/html/vendor/blackbit/data-director/lib/Pim/Helper.php(610): Blackbit\\DataDirectorBundle\\lib\\Pim\\Helper->createMapping()\n#2 /var/www/html/vendor/blackbit/data-director/lib/Pim/Helper.php(533): Blackbit\\DataDirectorBundle\\lib\\Pim\\Helper->handleDefinitionElement()\n#3 /var/www/html/vendor/blackbit/data-director/lib/Pim/Helper.php(401): Blackbit\\DataDirectorBundle\\lib\\Pim\\Helper->handleDefinitionElement()\n#4 /var/www/html/vendor/blackbit/data-director/Controller/MappingconfigController.php(94): Blackbit\\DataDirectorBundle\\lib\\Pim\\Helper->createFieldMappings()\n#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Blackbit\\DataDirectorBundle\\Controller\\MappingconfigController->getConfigAction()\n#6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#7 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#8 /var/www/html/public/index.php(36): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#9 {main}"
}
```

Problem in lib/Pim/Helper.php:3419:
```PHP
if ($def->getAssetsAllowed()) {
                $assetTypes = (array)$def->getAssetTypes();
                if (count($assetTypes) === 0) {
                    $assetTypes = ['asset'];
                }

                foreach ($assetTypes as $allowedAssetType) {
                    $allowedAssetType = $allowedAssetType['assetTypes'];
```

Possible solution:
```PHP
if ($def->getAssetsAllowed()) {
                $assetTypes = (array)$def->getAssetTypes();
                if (count($assetTypes) === 0) {
                  $assetTypes = [['assetTypes' => 'asset']];
                }

                foreach ($assetTypes as $allowedAssetType) {
                    $allowedAssetType = $allowedAssetType['assetTypes'];

**Comment by BlackbitDevs** [comment]
Is fixed in 3.5.47.
Thanks for notifying and even more for providing solution ;)
