### ISSUE TITLE
Unable to process item: TypeError: Pimcore\Model\Element\Service::getValidKey(): Argument #1 ($key) must be of type string, null given,

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#188]
I have definition for Path like this:
![image](https://github.com/user-attachments/assets/0618f569-6347-411f-9693-c5eae19c6018)

and such transformation:

```
use \Pimcore\Model\Element\Service;


$sizeIDS = [1106, 1049, 1173];

$attrId = $params['rawItemData']['AttrID']['value'];
$langId = $params['rawItemData']['LangID']['value'];

if ($langId != 1 || !in_array($attrId, $sizeIDS) || empty(trim($params['value']))) {
    return null;
}

return Service::getValidKey(trim($params['value']), 'object');

```

and I got error:

```
[INFO] --- Importing next raw data item
[INFO] Value for key field "path": null
[ALERT] Unable to process item: TypeError: Pimcore\Model\Element\Service::getValidKey(): Argument #1 ($key) must be of type string, null given, called in /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/lib/Pim/Item/FieldMapper/ElementKeyMapper.php on line 53 and defined in /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/pimcore/pimcore/models/Element/Service.php:935
Stack trace:
#0 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/lib/Pim/Item/FieldMapper/ElementKeyMapper.php(53): Pimcore\Model\Element\Service::getValidKey()
#1 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/lib/Pim/Item/FieldMappingManager.php(46): Blackbit\DataDirectorBundle\lib\Pim\Item\FieldMapper\ElementKeyMapper->map()
#2 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/lib/Pim/Item/Importer.php(1530): Blackbit\DataDirectorBundle\lib\Pim\Item\FieldMappingManager->map()
#3 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/lib/Pim/Item/Importer.php(5017): Blackbit\DataDirectorBundle\lib\Pim\Item\Importer->map()
#4 [internal function]: Blackbit\DataDirectorBundle\lib\Pim\Item\Importer->Blackbit\DataDirectorBundle\lib\Pim\Item\{closure}()
#5 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/lib/Pim/Item/Importer.php(5016): array_map()
#6 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/lib/Pim/Item/Importer.php(620): Blackbit\DataDirectorBundle\lib\Pim\Item\Importer->getKeyDatasets()
#7 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/lib/Pim/Item/Importmanager.php(977): Blackbit\DataDirectorBundle\lib\Pim\Item\Importer->import()
#8 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/lib/Pim/Item/Importmanager.php(670): Blackbit\DataDirectorBundle\lib\Pim\Item\Importmanager->processChunk()
#9 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/Command/ImportCompleteCommand.php(455): Blackbit\DataDirectorBundle\lib\Pim\Item\Importmanager->importDataport()
#10 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/blackbit/data-director/Command/ImportCompleteCommand.php(238): Blackbit\DataDirectorBundle\Command\ImportCompleteCommand::import()
#11 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/symfony/console/Command/Command.php(326): Blackbit\DataDirectorBundle\Command\ImportCompleteCommand->execute()
#12 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#13 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/symfony/framework-bundle/Console/Application.php(126): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/symfony/console/Application.php(324): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#15 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/symfony/framework-bundle/Console/Application.php(80): Symfony\Component\Console\Application->doRun()
#16 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/symfony/console/Application.php(175): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#17 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(49): Symfony\Component\Console\Application->run()
#18 /var/www/bikeshop.pimcore.dev.convert.no/www/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
#19 /var/www/bikeshop.pimcore.dev.convert.no/www/bin/console(20): require_once('...')
#20 {main}
```

It started to show after update from 3.7.37 to 3.7.57 (latest version)

As I know If I return "null" for any "Key" fields it should not process such record.
Why then we have this error now ?

**Comment by BlackbitDevs** [comment]
Fixed in 3.7.59.
